language: go

go:
  - 1.8

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - ./hack/verify-gofmt.sh
  - go test --cover $(go list ./... | grep -v /vendor/)
  - go build -o contactkey
  - ./contactkey -h
